networks:
  smartplug_net:
    name: smartplug_net

volumes:
  influxdb_data:
  influxdb_config:

services:
  mqtt_broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    ports:
      - "1884:1884"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - smartplug_net

  influxdb:
    image: influxdb:2.7.5
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=smartplugadmin # Must be at least 8 chars
      - DOCKER_INFLUXDB_INIT_ORG=smartplug_org
      - DOCKER_INFLUXDB_INIT_BUCKET=smartplug_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    networks:
      - smartplug_net

  ml_service:
    image: abhizx18324/ml-service:v1
    platform: linux/amd64
    container_name: ml_service
    environment:
      - MQTT_BROKER=mqtt_broker
      - MQTT_PORT=1884
    depends_on:
      - mqtt_broker
    networks:
      - smartplug_net

  ingestion_service:
    build: ./backend
    container_name: ingestion_service
    env_file:
      - .env
    environment:
      - MQTT_BROKER=mqtt_broker
      - MQTT_PORT=1884
      - INFLUX_URL=http://influxdb:8086
    depends_on:
      - mqtt_broker
      - influxdb
    networks:
      - smartplug_net

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "3000:80"
    networks:
      - smartplug_net

  digital_twin:
    build: 
      context: .
      dockerfile: digital-twin/Dockerfile
    container_name: digital_twin
    ports:
      - "3001:3001"
    environment:
      - MQTT_BROKER_URL=mqtt://mqtt_broker:1884
      - MQTT_BROKER=mqtt_broker
      - MQTT_PORT=1884
    depends_on:
      - mqtt_broker
    networks:
      - smartplug_net